"""Added company_name column to users table

Revision ID: 66ce308e7433
Revises: 8f36860f4661
Create Date: 2024-11-16 21:45:33.226013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ce308e7433'
down_revision = '8f36860f4661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
