"""Added relationship columns for users energyusage waste and travel

Revision ID: a80db4c0e5d0
Revises: 66ce308e7433
Create Date: 2024-11-16 21:55:14.420719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80db4c0e5d0'
down_revision = '66ce308e7433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_travel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kilometer_traveled', sa.Float(), nullable=True),
    sa.Column('fuel_efficiency', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electricity_bill', sa.Float(), nullable=True),
    sa.Column('natural_gas_bill', sa.Float(), nullable=True),
    sa.Column('fuel_bill', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waste_generated', sa.Float(), nullable=True),
    sa.Column('recycling_percantage', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste')
    op.drop_table('energy_usage')
    op.drop_table('business_travel')
    # ### end Alembic commands ###
